name: Free Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Enable RDP
        run: |
          net user runneradmin Password@123
          net localgroup administrators runneradmin /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Invoke-WebRequest https://raw.githubusercontent.com/fernandoaleman/rdp/main/ngrok.ps1 -OutFile ngrok.ps1
          powershell -ExecutionPolicy Bypass -File ngrok.ps1
